# permissions for end users to edit providers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: go-sdk
    app.kubernetes.io/managed-by: kustomize
  name: provider-editor-role
rules:
- apiGroups:
  - core.platformspec.io
  resources:
  - providers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.platformspec.io
  resources:
  - providers/status
  verbs:
  - get
