# permissions for end users to view softwaregroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: go-sdk
    app.kubernetes.io/managed-by: kustomize
  name: softwaregroup-viewer-role
rules:
- apiGroups:
  - core.platformspec.io
  resources:
  - softwaregroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.platformspec.io
  resources:
  - softwaregroups/status
  verbs:
  - get
