apiVersion: core.platformspec.io/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: go-sdk
    app.kubernetes.io/managed-by: kustomize
  name: cluster-sample
spec:
  # TODO(user): Add fields here
